### ISSUE TITLE
integration.kafka 消费者接收不到数据

### ISSUE THREAD

**Issue by pmsg863** [xho22/spring-boot-dubbo-mongo-mybatis-kafka-liquibase#1]
楼主：
       最近在做springboot与kafka的集成，使用demo里的示例，数据可以发往kafka，用bin/kafka-console-consumer.sh也可以接收到，但是从pollableChannel却拿不到数据。

`
   @Bean
    public OffsetManager offsetManager() {
        ZookeeperConnect zkc = new ZookeeperConnect(this.zookeeperConnect);
        zkc.setZkConnectionTimeout("30000");
        zkc.setZkSessionTimeout("30000");

```
    return new KafkaTopicOffsetManager(zkc, "si-offsets");
}

@Bean
public KafkaMessageListenerContainer container(OffsetManager offsetManager) throws Exception {
    final KafkaMessageListenerContainer kafkaMessageListenerContainer = new KafkaMessageListenerContainer(
            kafkaBrokerConnectionFactory(), this.topic/*topics.split(",")*/);
    kafkaMessageListenerContainer.setOffsetManager(offsetManager);
    kafkaMessageListenerContainer.setMaxFetch(100);
    kafkaMessageListenerContainer.setConcurrency(1);
    return kafkaMessageListenerContainer;
}

@Bean
public KafkaMessageDrivenChannelAdapter adapter(KafkaMessageListenerContainer container) {
    KafkaMessageDrivenChannelAdapter kafkaMessageDrivenChannelAdapter =
            new KafkaMessageDrivenChannelAdapter(container);
    StringDecoder decoder = new StringDecoder();
    kafkaMessageDrivenChannelAdapter.setKeyDecoder(decoder);
    kafkaMessageDrivenChannelAdapter.setPayloadDecoder(decoder);
    kafkaMessageDrivenChannelAdapter.setOutputChannel(fromKafka());
    return kafkaMessageDrivenChannelAdapter;
}

 @Bean
public PollableChannel fromKafka() {
    QueueChannel queueChannel = new QueueChannel();
    return queueChannel;
}

@Bean
public TopicCreator topicCreator() {
    return new TopicCreator(this.topic, this.zookeeperConnect);
}
```

public synchronized void receive() {
        Message<?> received = null;
        received = pollableChannel.receive(10000);
        System.out.println(received);
    }

```
@Override
public void run() {
    logger.info("启动kafka消费线程");
    while (true) {
        receive();
    }
}  
```

`
       希望各位了解的可以帮助我，谢谢。

**Comment by xho22** [comment]
都快一年前的东西了，今天居然有了第一条issue。
我刚才特地试了一下，我这边是通的，当时忘记单元测试的代码没有提交到GIT上，
但调试代码在com.ubankers.userservice.configuration.mq.kafka.ApplicationKafkaConfigurations里面有的，有个main方法。

如果还是不行，建议把日志发一下

**Comment by pmsg863** [comment]
感谢，真抱歉，没有及时回复，这几天出差在外，处理别的项目。

我再测试了下你的代码，使用新建的Topic来进行收发，一开始的几次可以正常进行。
不过再多调试几次后，程序可发送数据，但是不能接收数据，不过用kafka-console-consumer.sh可以收到数据。

我初步判断是在Partition理解不到位，导致的后面问题。我Topic是使用--replication-factor 2 --partitions 2新建的。
